cgov_mail.settings:
  type: config_object
  label: 'Email Settings'
  mapping:
    contact_form_recipient:
      type: text
      label: 'Email form Recipient'
    re-captcha:
      type: text
      label: 'Re-captcha key'
